<template>
 <div>
   <div v-for="employment in employments" :key="employment.id">
     <edit-employment-component/>
     <remove-employment-component/>
   </div>
 </div>
</template>
<script>
export default {
 props:{
  user:{
   type:Object,
   required:true
  }
 },
 data(){
  return{
   employments:[]
  }
 },
 mounted(){
  this.getEmploymentHistory();
 },
 methods:{
  getEmploymentHistory(){
   axios.get('/employment/all',{params:{user:this.user}})
   .then(res=>{
    this.employments=res.data.employments;
   })
  }
 }
}
</script>